### ISSUE TITLE
Add Ukrainian translation templates

### ISSUE THREAD

**Issue by Symbian9** [jimevins/glabels-qt#20]
Please, add `*_uk.ts` templates to translation folder

- https://github.com/jimevins/glabels-qt/tree/master/translations

Then I will try add Ukrainian locales to *gLabels* ;-)

**Comment by mariobl** [comment]
It is quite simple: Just use the files glabels_C.ts and templates_C.ts as a template for your work. You should use a translation editor with native *.ts support, like Qtlinguist or Virtaal. Once you are finished (or at least partially finished), post your file(s) here.

Currently we are looking for a reasonable translation management platform. Maybe Transifex, Zanata or anything similar... Once the decision is made, we will inform you. This will simplify things a bit.

@Jim: BTW, what would happen if just one file is available for a certain language? Would it break the build? I know about a similar case in GTK+. There are two folders with po files, »po« and »po-properties«. Available languages must be present in both folders, otherwise the build fails.

**Comment by Symbian9** [comment]
> BTW, what would happen if just one file is available for a certain language? Would it break the build?

Think, it should NOT break the build.

Look here:

- https://github.com/OpenOrienteering/mapper/tree/master/translations

**Comment by jimevins** [comment]
> @jimevins : BTW, what would happen if just one file is available for a certain language? Would it break the build? I know about a similar case in GTK+. There are two folders with po files, »po« and »po-properties«. Available languages must be present in both folders, otherwise the build fails.

No, this will not break the build as long as the file is not listed in TRANSLATION_FILES.txt.  It will fall-back to the C locale for those translations.  As I recall, you provided the glabels_de_DE.ts file several days before the templates_de_DE.ts -- it did not break the build.

**Comment by jimevins** [comment]
I have added the skeletal translation files to master.  (842c5012f5a3c082e51cdc01fd6071df5dd5a3c4)

**Comment by mariobl** [comment]
> Attention: As long as Weblate produces quite different output than the Qt tools (WeblateOrg/weblate#1118), it is not recommended to use Qt Linguist: It will lead to some noise in the git change log.

If this leads to forcing translators to use the web editor (in case of the generated ts files are really annoying), then it's a no-go. I'm a translator for ages, and I still prefer local tools like Poedit or Qtlinguist. Well, I don't know how Transifex or Zanata handle *.ts files. Maybe we run into the same problem there...
