### ISSUE TITLE
Barcode object properties EAN-13

### ISSUE THREAD

**Issue by turubanov** [jimevins/glabels-qt#79]
For a barcode object (type EAN-13), the "Show text" and "Checksum" checkbox cannot be unchecked.
![image](https://user-images.githubusercontent.com/9862623/70141001-18399d80-16a7-11ea-983a-a0118d37c4bb.png)

glabels-3.99-master552
Windows 10 Pro 10.0.18362

**Comment by jimevins** [comment]
This is because the glbarcode/builtin backend does not currently support changing these options for the UPC/EAN barcode types.

I can understand why you may want to toggle the text, but I am not sure why you would want to turn off the check digit -- without it, the barcode would not be valid.

Perhaps you expect the check digit to already be in your data -- which would be a fair use-case.  The zint backend's EAN barcode type actually handles both use cases pretty well.   If you provide 12 digits it automatically adds the check digit and if you provide 13 digits it simply validates the check digit you provided.  Unfortunately, I have not yet been successful in linking against the zint library for Windows on Appveyor -- I am a fish-out-of-water on Windows.

**Comment by turubanov** [comment]
The checksum is not so important, I can prepare data with it and without it. But remove the text ... I will wait, thanks.

**Comment by jimevins** [comment]
I believe this can now be closed.

**Comment by turubanov** [comment]
Thank you very much!
